import "./globals.css";
import type { ReactNode } from "react";
import type { Metadata } from "next";
import { getBaseUrl } from "@/utils/get-base-url";

export const metadata = {
  metadataBase: new URL(
    getBaseUrl({
      isServer: true,
    })
  ),
  title: "Next App",
  description: "Generated by @chia-stack/nextjs-app template",
} satisfies Metadata;

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
